/*
*
* Copyright(c) {2015 - 2025} Texas Instruments Incorporated
*
* All rights reserved not granted herein.
*
* Limited License.
*
* Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
* license under copyrights and patents it now or hereafter owns or controls to make,
* have made, use, import, offer to sell and sell("Utilize") this software subject to the
* terms herein.  With respect to the foregoing patent license, such license is granted
* solely to the extent that any such patent is necessary to Utilize the software alone.
* The patent license shall not apply to any combinations which include this software,
* other than combinations with devices manufactured by or for TI("TI Devices").
* No hardware patent is licensed hereunder.
*
* Redistributions must preserve existing copyright notices and reproduce this license
*(including the above copyright notice and the disclaimer and(if applicable) source
* code license limitations below) in the documentation and/or other materials provided
* with the distribution
*
* Redistribution and use in binary form, without modification, are permitted provided
* that the following conditions are met:
*
* *       No reverse engineering, decompilation, or disassembly of this software is
* permitted with respect to any software provided in binary form.
*
* *       any redistribution and use are licensed by TI for use only with TI Devices.
*
* *       Nothing shall obligate TI to provide you with source code for the software
* licensed and provided to you in object code.
*
* If software source code is provided to you, modification and redistribution of the
* source code are permitted provided that the following conditions are met:
*
* *       any redistribution and use of the source code, including any resulting derivative
* works, are licensed by TI for use only with TI Devices.
*
* *       any redistribution and use of any object code compiled from the source code
* and any resulting derivative works, are licensed by TI for use only with TI Devices.
*
* Neither the name of Texas Instruments Incorporated nor the names of its suppliers
*
* may be used to endorse or promote products derived from this software without
* specific prior written permission.
*
* DISCLAIMER.
*
* THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES(INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT(INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/


/**
@file      tidl_forceNegativeTest.h
brief      This file defines kernel-specific ENUM flags to verify whether the safety flag is set. \n
           This interface ensuring kernel pointer parameters are set to NULL for safety fail checks.

@version 0.1 Jan 2025 : Initial Code
*/
#ifndef TIDL_FORCENEGATIVETEST_H
#define TIDL_FORCENEGATIVETEST_H

#define TIDL_SAFETY_FLAG_ALG_2DMEMCPY_FORCE_INTALGHNDLE_NULL (1000)
#define TIDL_SAFETY_FLAG_ALG_ACT_FORCE_2DMEMCPYSTATE_INVALID (1001)
#define TIDL_SAFETY_FLAG_ALG_ACT_FORCE_ALGSTATE_INVALID (1002)
#define TIDL_SAFETY_FLAG_ALG_ACT_FORCE_INITDMAUTILSTATE_INVALID (1003)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_ALGLAYERSSIZE (1004)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_GCHELPERHNDLE_NULL (1005)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_LAYERTYPE_INVALID (1006)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_LOOP_FLAG_CHECK (1007)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_PTRWORKLOAD_NULL (1008)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_REFSCRATCHBUFFSIZE (1009)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_SCRATCHBUFFSIZE (1010)
#define TIDL_SAFETY_FLAG_ALG_DEACT_FORCE_ALGSTATE_INAVALID (1011)
#define TIDL_SAFETY_FLAG_ALG_DEACT_FORCE_INTALGHNDLE_NULL (1012)
#define TIDL_SAFETY_FLAG_ALG_FREE_FORCE_LSTHNDLE_INVALID (1013)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_L3BASEPTR_NULL (1014)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_LAYERTYPE_INVALID (1015)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_LYERSPRMMEMTBOFS_MAX (1016)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_NUMODLAYER_INVALID (1017)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_OPTEXTMEML1_NULL (1018)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_PRMMEMTBOFS_MAX (1019)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_TRACEBUFPTR_NULL (1020)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_WHILEFLAG_ZERO (1021)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_WLUNIT_NULL (1022)
#define TIDL_SAFETY_FLAG_ALG_LAYERPROCESS_FORCE_REDUCELAYER (1023)
#define TIDL_SAFETY_FLAG_ALG_LAYERPROCESS_FORCE_REDUCELAYER_NULL (1024)
#define TIDL_SAFETY_FLAG_ALG_LYERINIT_FORCE_STATUS_INVALID (1025)
#define TIDL_SAFETY_FLAG_ALG_PROC_FORCE_INTALGHNDLE_NULL (1026)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_DMACURIDX_INVALID (1027)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_GETEXECNUMLYR_NULL (1028)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_GETLYRSTATE_INVALID (1029)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_LNKPTR_NULL (1030)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_NUMLAYERS_ZERO (1031)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_SYNC_INVALID (1032)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_TRACEWRITE_INVALID (1033)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_WHILEFLAG_ZERO (1034)

#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_ALIGNMENT_ZERO (1100)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_DMAUTILSCNTX_NULL (1101)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_FLOWCNT_INVALID (1102)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_GRPID_INVALID (1103)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_GRPIDX_INVALID (1104)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_INPTRS_GC_TRACE_SCRATCHSIZE_INVALID (1105)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_INPTRS_INDATAPARAMS_NULL (1106)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_INPTRS_NC_TRACE_SCRATCHSIZE_INVALID (1107)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_INTALGHNDLE_NULL (1108)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_L2BASEPTR_NULL (1109)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_LNKTYPE_INVALID (1110)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_MCPYTR_NULL (1111)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_MOVENET_ALGLAYERPARAMS_NULL (1112)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_NUMLAYERS_MAX (1113)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_NUMLAYERS_MIN (1114)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_OUTDATABUF_NUMLAYERS_MAX (1115)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_OUTPRTS_INVALID_DATATYPE (1116)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_OUTPTRS_NULL (1117)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_PITCHWIDTH_INVALID (1118)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_PREMPHNDLE_NULL (1119)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_PREMPHNDLEDDR_NULL (1120)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_PRVCNTX_NULL (1121)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_WLSUPERGRP_NULL (1122)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_WLUNIT_NULL (1123)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_WTMEMBASEPTR_NULL (1124)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_ZEROVEC1K_NULL (1125)
#define TIDL_SAFETY_FLAG_ALGUTILS_GETPAD_FORCE_PADPARAMS_NULL (1126)

#define TIDL_SAFETY_FLAG_ALLOC_FORCE_NET_NULL (1127)
#define TIDL_SAFETY_FLAG_ALLOC_FORCE_NETVERSION (1128)
#define TIDL_SAFETY_FLAG_ALLOC_FORCE_VPRINTF_NULL (1129)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_FUNCSTYLE (1200)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_KERNEL_DST_32BIT (1201)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_KERNEL_DST_NULL (1202)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_KERNEL_SRC_32BIT (1203)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_KERNEL_SRC_NULL (1204)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_SOURCE_NULL (1205)

#define TIDL_SAFETY_FLAG_BATCHNORM_FLOATNONLINEAR_FORCE_NETVERSION (1300)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_BATCHNORM_CORE_ERROR_FLOAT_REFERENCE (1301)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_BATCHNORM_CORE_ERROR_FLOWCTRL (1302)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_BATCHNORM_CORE_ERROR_NONLUT_REFERENCE (1303)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_BATCHNORM_CORE_USE_DDR_MEM_FOR_LUT (1304)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_DEVICE_INIT_IALG_EFAIL (1305)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_ERR_INVALID_TYPE (1306)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_EXECUTE_POINTER_NULL (1307)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_HANDLE_NULL (1308)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_INIT_LUTPARAMS_MEM_POINTER_NULL (1309)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_REF_BATCHNORM_CORE_ACCMEM_SCRATCH_NULL (1310)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_WEIGHT_PARAM_ZERO (1311)
#define TIDL_SAFETY_FLAG_BATCHNORM_NONLUTCORE_FORCE_NETVERSION (1312)

#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_FUNC_STYLE_ERROR (1400)
#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_INBATCH_OUTBATCH_NULL (1401)
#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_KERNEL_HANDLE_NULL (1402)
#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_KERNEL_SRC_NULL (1403)
#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_NUMBATCHES_ZERO (1404)

#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_FUNC_STYLE_ERROR (1500)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_KERNEL_DST_ERROR_TYPE (1501)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_KERNEL_HANDLE_NULL (1502)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_KERNEL_SRC_ERROR_TYPE (1503)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_KERNEL_SRC_NULL (1504)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_SRC_AND_DST_ADDR_NULL (1505)

#define TIDL_SAFETY_FLAG_CONCAT_FORCE_DST_ADDR_32BIT (1600)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_INCORRECT_PROC_ELEM_SIZE (1601)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_KERNEL_32BIT_DATATYPE (1602)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_KERNEL_32BIT_DATATYPE_EXEC (1603)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_NUMINBUFS_ZERO (1604)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_SCRATCH_SIZE (1605)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_SRC_AND_DST_ADDR_NULL (1606)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_SRC_KERNEL_NULL (1607)

#define TIDL_SAFETY_FLAG_CONST_GCHELPERHANDLE_NULL (1700)

#define TIDL_SAFETY_FLAG_CONV_ROWFLOW_SRC_AND_SINK_JOINT_NULL (1800)
#define TIDL_SAFETY_FLAG_CONV2D_BASE_FORCE_ALGLAYER_WL_NULL (1801)
#define TIDL_SAFETY_FLAG_CONV2D_DEVICE_FORCE_ALGLAYER_WL_NULL (1802)
#define TIDL_SAFETY_FLAG_CONV2D_DEVICE_FORCE_LAYERSPECIFICPARAMS_WL_NULL (1803)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_COEFF_SRC_NULL (1804)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_INVALID_BIASPTR (1805)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_INVALID_CONVTYPE (1806)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_INVALID_DATATYPE (1807)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_OUTDATATYPE (1808)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_OUTPTR_NULL (1809)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_REF_ERROR_FUNCTION (1810)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_REF_INVALID_INDATATYPE (1811)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_REF_INVALID_OUTDATATYPE (1812)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_SCRATCH_SIZE (1813)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_GETWEIGHTADDR_FAIL (1814)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_HIGHPRE_REORDERWEIGHTS_ARGS_MMA_FAIL (1815)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_KERNEL_SETUP_ARGS_VARIANTS_FAIL (1816)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_KERNEL_SETUP_FAIL (1817)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_REORDERWEIGHTS_ARGS_MMA_FAIL (1818)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_ZERO_PADCOL_PADROW (1819)

#define TIDL_SAFETY_FLAG_CUSTOM_FORCE_INDATAPTR_NULL (1900)
#define TIDL_SAFETY_FLAG_CUSTOM_FORCE_OPTIMISEEXTMEM_NULL (1901)

#define TIDL_SAFETY_FLAG_DATAFLOW_FORCE_HANDLESIZE_DDR_MAX (2000)
#define TIDL_SAFETY_FLAG_DATAFLOW_FORCE_WLLOOPITR_NULL (2001)
#define TIDL_SAFETY_FLAG_DATAFLOW_FORCE_WORKLOADUNIT_NULL (2002)

#define TIDL_SAFETY_FLAG_DCN_FORCE_BIAS_DISABLE (2100)
#define TIDL_SAFETY_FLAG_DCN_FORCE_COEFF_BUFFER_SPACE_L2 (2101)
#define TIDL_SAFETY_FLAG_DCN_FORCE_DATATYPE_ERROR (2102)
#define TIDL_SAFETY_FLAG_DCN_FORCE_DATATYPENSIZE_ERROR (2103)
#define TIDL_SAFETY_FLAG_DCN_FORCE_FUNC_STYLE (2104)
#define TIDL_SAFETY_FLAG_DCN_FORCE_INVALID_MASK_DIMS (2105)
#define TIDL_SAFETY_FLAG_DCN_FORCE_INVALID_OFFSET_DIMS (2106)
#define TIDL_SAFETY_FLAG_DCN_FORCE_KERNEL_HANDLE_NULL (2107)
#define TIDL_SAFETY_FLAG_DCN_FORCE_LINK_SOURCE_BUFFER_FM (2108)
#define TIDL_SAFETY_FLAG_DCN_FORCE_NULL_OUTPTR (2109)
#define TIDL_SAFETY_FLAG_DCN_FORCE_PARENT_BUFFER_TYPE_FM (2110)
#define TIDL_SAFETY_FLAG_DCN_FORCE_SCRATCH_SIZE_ZERO (2111)
#define TIDL_SAFETY_FLAG_DCN_FORCE_SMALLER_SCRATCH_SIZE (2112)

#define TIDL_SAFETY_FLAG_DECONV_FORCE_16B_BIASPARAMSIZE (2200)
#define TIDL_SAFETY_FLAG_DECONV_FORCE_64B_WEIGHTSELEMENTSIZEINBITS (2201)
#define TIDL_SAFETY_FLAG_DECONV_FORCE_8B_BIASPARAMSIZE (2202)
#define TIDL_SAFETY_FLAG_DECONV_FORCE_BUFSCRATCHSIZE (2203)
#define TIDL_SAFETY_FLAG_DECONV2D_FORCE_REF_INVALID_OUTDATATYPE (2204)

#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_COMMONPROCESS_WL_NULL (2300)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_DMAUTILSCONTEXT_NULL (2301)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_OUITPUT_SIZE_ALLOC (2302)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_OUITPUT_SIZE_INIT (2303)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_OUITPUT_SIZE_NEG (2304)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_OUTPRT_NULL (2305)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_PAD_DMAUTILSCONTEXT_NULL (2306)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_PADPARAM_PAD_TYPE (2307)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_SCRATCHDATASIZE_ALLOC (2308)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_SCRATCHDATASIZE_INIT (2309)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_SCRATCHDATASIZE_NEG (2310)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_SHIFT_NULL (2311)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_WL_NULL (2312)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_WLLOOPITR_NULL (2313)

#define TIDL_SAFETY_FLAG_ELTWISE_ELTWISETYPE (2400)
#define TIDL_SAFETY_FLAG_ELTWISE_FORCE_FUNC_STYLE (2401)
#define TIDL_SAFETY_FLAG_ELTWISE_FORCE_KERNEL_HANDLE_NULL (2402)
#define TIDL_SAFETY_FLAG_ELTWISE_FORCE_NUMINDATA (2403)
#define TIDL_SAFETY_FLAG_ELTWISE_NUMINDATA_ERROR (2404)
#define TIDL_SAFETY_FLAG_ELTWISEADD_ELTWISE_NUMINDATA_ERROR_HW_INIT (2405)
#define TIDL_SAFETY_FLAG_ELTWISEADD_ELTWISE_NUMINDATA_ERROR_HW_PROC_INIT (2406)
#define TIDL_SAFETY_FLAG_ELTWISEADD_ELTWISE_TYPE_ERROR_HW_PROC_INIT (2407)
#define TIDL_SAFETY_FLAG_ELTWISEADD_FORCE_DSTADDR_NULL (2408)
#define TIDL_SAFETY_FLAG_ELTWISEADD_FORCE_SRC_NATC_NULL (2409)
#define TIDL_SAFETY_FLAG_ELTWISEADD_NUMBYTES_ERROR_HW_INIT (2410)
#define TIDL_SAFETY_FLAG_ELTWISEADD_NUMBYTES_ERROR_HW_PROC_INIT (2411)
#define TIDL_SAFETY_FLAG_ELTWISEMINMAX_FORCE_DST_NUMBYTES_ERROR (2412)
#define TIDL_SAFETY_FLAG_ELTWISEMINMAX_FORCE_SRC_NATC_NULL (2413)
#define TIDL_SAFETY_FLAG_ELTWISEMINMAX_FORCE_SRC_NUMBYTES_ERROR (2414)
#define TIDL_SAFETY_FLAG_ELTWISEMINMAX_INPUT_SIGNED_ERROR_CASE (2415)
#define TIDL_SAFETY_FLAG_ELTWISEPROD_FORCE_DST_NATC_NUMBYTES_ERROR (2416)
#define TIDL_SAFETY_FLAG_ELTWISEPROD_FORCE_SRC_NATC_NULL (2417)

#define TIDL_SAFETY_FLAG_GATHER_DATATYPE_ERROR (2500)
#define TIDL_SAFETY_FLAG_GATHER_FLOAT_ERROR (2501)

#define TIDL_SAFETY_FLAG_GC_HELPER_FORCE_WL_UNIT_NULL (2600)

#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_FUNC_STYLE_ERROR (2700)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_ROUNDBIT_ZERO (2701)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRC_NULL_NATC_32BIT_ASYM_NP2_TFL (2702)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRC_NULL_NATC_32BIT_FIXED_NP2_QUANT (2703)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRCADDR_32BIT (2704)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRCADDR_32BIT_KERNEL (2705)

#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_DATATYPE_ERROR (2800)
#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_FUNC_STYLE (2801)
#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_KERNEL_HANDLE_NULL (2802)
#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_SCRATCH_SIZE (2803)
#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_UNSUPPORTED_MODE (2804)

#define TIDL_SAFETY_FLAG_INNERPRODUCT_32BIT_INDATA (2900)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_32BIT_INDATA_FOR_BIAS (2901)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_32BIT_OUTDATA (2902)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_CHANNEL_LIMIT_EXCEEDED (2903)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_UTILS_CONTEXT_3D_CONFIGURE_FAIL (2904)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_UTILS_CONTEXT_INPUT_3D_DECONFIGURE_FAIL (2905)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_UTILS_CONTEXT_NULL (2906)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_UTILS_CONTEXT_NULL_INNER_LOOP (2907)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_BIASPTR_NULL (2908)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_DATATYPE_64B (2909)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INELEMENTTYPE_WORD (2910)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INPTR_INFER_NULL (2911)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INPTR_NULL (2912)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INVALID_INBDATA_DATATYPE (2913)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INVALID_SCRATCHSIZE (2914)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_ROUNDSAT_MMA_ZERO_SHIFT_BITS (2915)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_HANDLE_NULL_INIT_ALLOC (2916)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_L1_MEMORY (2917)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_MEMORY_BIAS (2918)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_MEMORY_FOR_HANDLE (2919)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_MEMORY_INFEAT_MAP (2920)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_MEMORY_KERNEL (2921)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_MMALIB_HANDLE_NULL (2922)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_MMALIB_HANDLE_NULL_CHECKPARAMS (2923)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_REF_ERROR_HANDLE_NULL (2924)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_SYSMEMS_L2_NULL_INNER_LOOP (2925)

#define TIDL_SAFETY_FLAG_LAYER_INIT_FORCE_LAYERTYPE_INVALID (3000)

#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_BUFFERDATASIZE_MAX (3100)
#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_NET_VERSION_MODIFY (3101)
#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_SRC_AND_DST_ADDR_NULL (3102)
#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_SRC_NULL (3103)
#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_SRC_NULL_V2 (3104)
#define TIDL_SAFETY_FLAG_LAYERNORM_FUNC_STYLE_ERROR (3105)
#define TIDL_SAFETY_FLAG_LAYERNORM_KERNEL_HANDLE_NULL (3106)
#define TIDL_SAFETY_FLAG_LAYERNORM_NATC_DATATYPE_ERROR (3107)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR (3108)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_C7X (3109)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_EXEC (3110)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_INNERLOOP (3111)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_V2 (3112)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_V2_EXEC (3113)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_V2_INNERLOOP (3114)
#define TIDL_SAFETY_FLAG_LAYERNORM_SCRATCH_SIZE_ERROR (3115)
#define TIDL_SAFETY_FLAG_LAYERNORM_SCRATCH_SIZE_ERROR_C7X (3116)
#define TIDL_SAFETY_FLAG_LAYERNORM_SCRATCH_SIZE_ERROR_V2 (3117)

#define TIDL_SAFETY_FLAG_MATMUL_FORCE_INVALID_SRCBUF_DATA_ID (3200)
#define TIDL_SAFETY_FLAG_MATMUL_FORCE_WORKLOADUNIT_NULL (3201)

#define TIDL_SAFETY_FLAG_OD_FORCE_CODETYPE (3300)
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE (3301)
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE_16BIT (3302)
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE_16BITV2 (3303)
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE_TIDL_SinglePrecFloat (3304)
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE_TIDL_UnsignedDoubleWord (3305)
#define TIDL_SAFETY_FLAG_OD_FORCE_HEADSIZE (3306)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_COUNTM (3307)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_DATALAYOUT (3308)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_FilterNotInRangeBox (3309)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_FUNCSTYLE (3310)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_INIT_CHECKPARAMS (3311)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_SCORECONVERT (3312)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_SCORECONVERT_INIT (3313)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_SRC_FLOAT (3314)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_TOPM (3315)
#define TIDL_SAFETY_FLAG_OD_FORCE_MAXSCORE (3316)
#define TIDL_SAFETY_FLAG_OD_FORCE_MINSCORE (3317)
#define TIDL_SAFETY_FLAG_OD_FORCE_MINSCOREV2 (3318)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_COUNTMLIST (3319)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_COUNTMLISTACC (3320)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_FEATMAXMINVAL (3321)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_NMSKEPTINDICES (3322)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_PRED (3323)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TEMPSCORE (3324)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPKBBOX (3325)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPKBBOX_INTMEM (3326)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPKINDICES (3327)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPKSCORE (3328)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPMINDICES (3329)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPMINDICESSORTED (3330)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPMSCORE (3331)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPMSCORESORTED (3332)
#define TIDL_SAFETY_FLAG_OD_FORCE_TOPMDDR (3333)
#define TIDL_SAFETY_FLAG_OD_FORCE_TOTCNT_INVALID (3334)
#define TIDL_SAFETY_FLAG_OD_FORCE_TOTCNTFLT_INVALID (3335)
#define TIDL_SAFETY_FLAG_OD_FORCE_TOTCNTSHORT_INVALID (3336)

#define TIDL_SAFETY_FLAG_PAD_FORCE_L2_SCRATCHSIZE_MAX (3400)
#define TIDL_SAFETY_FLAG_PAD_FORCE_L3_SCRATCHSIZE_MAX (3401)

#define TIDL_SAFETY_FLAG_POOLING_FORCE_ACT_TYPE_ERROR (3500)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_BUFFER_PREDICATE_NULL (3501)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_DATATYPE_CHANGE (3502)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_DST_ADDRESS_NULL (3503)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_FUNC_STYLE_ERROR (3504)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_HANDLE_NULL (3505)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_KERNEL_HANDLE_NULL (3506)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_MAX_NUM_OF_LAYERS (3507)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_NEGATIVE_TEST_CI_FLOW (3508)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_NUMBYTES_3 (3509)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_NUMBYTES_4 (3510)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_NUMBYTES_8 (3511)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_PAD_OTF_FALSE (3512)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_POOL_TYPE_ERROR (3513)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_SCRATCH_SIZE (3514)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_SRC_ADDRESS_NULL (3515)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_SRCADDR_32BIT (3516)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_WORKLOADUNIT_NULL (3517)

#define TIDL_SAFETY_FLAG_REDUCE_FORCE_AXIS_MAX (3600)
#define TIDL_SAFETY_FLAG_REDUCE_FORCE_AXIS_WIDTH (3601)
#define TIDL_SAFETY_FLAG_REDUCE_FORCE_FUNC_STYLE (3602)
#define TIDL_SAFETY_FLAG_REDUCE_FORCE_PTRTOSCARTCH_NULL (3603)
#define TIDL_SAFETY_FLAG_REDUCE_FORCE_SRC_DST_ADDR_NULL (3604)

#define TIDL_SAFETY_FLAG_RESHAPE_FORCE_ELEMENTTYPE_MAX (3700)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_DATATYPE_ERROR (3701)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_DDR_SCRATCHSIZE_MAX (3702)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_FLOWCONTROL (3703)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_INVLID_RESIZE_MODE (3704)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_L3_SCRATCHSIZE_MAX (3705)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_PROCESSNEW_HEIGHTRATIO_ZERO (3706)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_PROCESSNEW_WIDTHRATIO_ZERO (3707)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_PROCESSSP_HEIGHTRATIO_ZERO (3708)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_PROCESSSP_WIDTHRATIO_ZERO (3709)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_RESIZEVALUE (3710)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_SOURCE_NULL (3711)

#define TIDL_SAFETY_FLAG_SCATTER_FORCE_32B_DATATYPE (3800)
#define TIDL_SAFETY_FLAG_SCATTER_FORCE_OUTPTR_NULL (3801)
#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_FLOAT_INPUT_ERROR (3802)
#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_MEM_FOR_TINY_TABLE_ERROR (3803)
#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_NULL_POINTER_ERROR (3804)
#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_NUM_OUT_ROW_ERROR (3805)
#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_NUMDIM_ERROR (3806)
#define TIDL_SAFETY_FLAG_SCATTERND_AXIS_AND_DATATYPE_ERROR (3807)
#define TIDL_SAFETY_FLAG_SCATTERND_LARGE_NUMLINES_ERROR (3808)

#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_DMA_CONTEXT_NULL (3900)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_DMA_TR_NULL (3901)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_NUMSPLITS_DMA_CONTEXT_NULL (3902)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_NUMSPLITS_DMA_TR_NULL (3903)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_TRMEM1_NULL (3904)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_TRMEM2_NULL (3905)

#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_AXIS (4000)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_AXIS_MAX (4001)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_FUNCSTYLE_ERROR (4002)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_HANDLE_NULL (4003)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_INSUFFICIENT_SCRATCHMEM_ERROR (4004)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_KERNEL_HANDLE_NULL (4005)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_MEMPTR_NULL (4006)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_SRCADDR_NULL (4007)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_TRANSPOSE (4008)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_TRANSPOSE_ZERO (4009)

#define TIDL_SAFETY_FLAG_TIDLRT_ALG_GCINFO_NULL (4100)
#define TIDL_SAFETY_FLAG_TIDLRT_ALLOC_FORCE_TRACEBUF_NULL (4101)
#define TIDL_SAFETY_FLAG_TIDLRT_INIT_FORCE_TRACEBUF_NULL (4102)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_CTRLCALL_TEST (4103)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_DMACNTX_NULL (4104)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_DMACREATE_NULL (4105)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_DMACURIDX_INVALID (4106)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_PADEDBUF_NULL (4107)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_PROCCNT_TEST (4108)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_QNTRNG_NULL (4109)

#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_AXIS (4200)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_AXIS_INIT (4201)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_DST_FLOAT (4202)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_FUNCSTYLE (4203)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_INIT_CHECKPARAMS (4204)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_SRC_INT16 (4205)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_SRC_INT8 (4206)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_SRC_UINT16 (4207)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_SRC_UINT8 (4208)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_WL_NULL (4209)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_LARGE_K (4210)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_NULLPTR_SCRATCH (4211)

#define TIDL_SAFETY_FLAG_TRANSPOSE_ALLOC_FORCE_NETVERSION (4300)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_Collapse_Dimensions (4301)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_DST_FLOAT (4302)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_FUNCSTYLE (4303)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_INIT_CHECKPARAMS (4304)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_PERM (4305)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_SRC_INT16 (4306)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_SRC_INT8 (4307)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_SRC_UINT16 (4308)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_SRC_UINT8 (4309)
#define TIDL_SAFETY_FLAG_TRANSPOSE_INIT_FORCE_NETVERSION (4310)
#define TIDL_SAFETY_FLAG_TRANSPOSE_PROCESS_FORCE_NETVERSION (4311)

#define TIDL_SAFETY_FLAG_WL_ALLOCNCMPT_FORCE_FUNCPTR_NULL (4400)
#define TIDL_SAFETY_FLAG_WL_EXECINIT_FORCE_DMACURIDX_INVALID (4401)
#define TIDL_SAFETY_FLAG_WL_EXECINIT_FORCE_INITPARAM_NULL (4402)
#define TIDL_SAFETY_FLAG_WL_EXECINIT_FORCE_SYSMEMSIZES_ZERO (4403)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_DECONV_FORCE_1D_INVALID (4404)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_1D_INVALID (4405)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_GETPTR_NULL (4406)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_LNKSUBTYPE_INVALID (4407)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_PADCOLS_INVALID (4408)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_PADCOLS_REQ_INVALID (4409)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_PADROWS_INVALID (4410)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_SNKSHAPETYPE_INVALID (4411)
#define TIDL_SAFETY_FLAG_WL_WLPROC_FORCE_DMAUTILS_NULL (4412)
#define TIDL_SAFETY_FLAG_WL_XFRLNK_FORCE_DIFFSRCSTAGE_INVALID (4413)
#define TIDL_SAFETY_FLAG_WL_XFRLNK_FORCE_DIFFSRCSTAGE2_INVALID (4414)
#define TIDL_SAFETY_FLAG_WL_XFRLNKINTER_FORCE_FMT16TO8B_INVALID (4415)
#define TIDL_SAFETY_FLAG_WL_XFRLNKINTER_FORCE_FMT8TO16B_INVALID (4416)
#define TIDL_SAFETY_FLAG_WL_XFRLNKINTER_FORCE_FMT8TO32B_INVALID (4417)
#define TIDL_SAFETY_FLAG_WORKLOAD_FORCE_REF_BUF_NOT_FOUND (4418)
#define TIDL_SAFETY_FLAG_WORKLOAD_REF_EXEC_GCHELPERHANDLE_NULL (4419)
#define TIDL_SAFETY_FLAG_WORKLOAD_REF_EXEC_PBUFLIST_NULL (4420)
#define TIDL_SAFETY_FLAG_WORKLOAD_REF_EXEC_TENSORPOSITION_NULL (4421)

#endif /* TIDL_FORCENEGATIVETEST_H */
