/*
 *  Copyright (C) 2026 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
/**
 * \ingroup TISCI
 * \defgroup tisci_sec_isc_ids tisci_sec_isc_ids
 *
 * DMSC controls the power management, security and resource management
 * of the device.
 *
 *
 * @{
 */
/**
 *
 *  \brief  This file contains:
 *
 *          WARNING!!: Autogenerated file from SYSFW. DO NOT MODIFY!!
 * Copyright (C) 2026 Texas Instruments Incorporated - http://www.ti.com/
 */

/**
 *
 * \brief TISCI message definitions for ISC PrivID configuration.
 *
 * This message configures PrivIDs for a hardware accelerator ISC subsystem
 * after the subsystem has been powered on.
 *
 * \note The target subsystem must be fully powered on before calling this
 *       service. Calling while the subsystem is powered off will result
 *       in undefined system behavior.
 */

#ifndef TISCI_SEC_ISC_IDS_H_
#define TISCI_SEC_ISC_IDS_H_


/** Subsystem IDs for TISCI_MSG_CONFIGURE_ISC_IDS */
#define TISCI_ISC_IDS_SUBSYS_VPAC0  (0U)        /**< VPAC0: valid on J721S2 and J784S4 */
#define TISCI_ISC_IDS_SUBSYS_VPAC1  (1U)        /**< VPAC1: behavior is undefined on SoCs without a second VPAC instance */
#define TISCI_ISC_IDS_SUBSYS_DMPAC  (2U)        /**< DMPAC: valid on J721S2 and J784S4 */

/**
 * \brief Request for TISCI_MSG_CONFIGURE_ISC_IDS
 *
 * \param hdr           Standard TISCI header
 * \param subsystem_id  Subsystem to configure
 */
struct tisci_msg_configure_isc_ids_req {
    struct tisci_header    hdr;
    uint32_t            subsystem_id;
} __attribute__((__packed__));

/**
 * \brief Response for TISCI_MSG_CONFIGURE_ISC_IDS
 *
 * \param hdr  Standard TISCI header (ACK/NAK)
 */
struct tisci_msg_configure_isc_ids_resp {
    struct tisci_header hdr;
} __attribute__((__packed__));

#endif /* TISCI_SEC_ISC_IDS_H_ */

/* @} */
