PSDK_PATH ?= $(abspath ..)
PSDK_BUILDER_PATH ?= $(PSDK_PATH)/sdk_builder

# Inherit common build flags from root repo in SDK
include $(PSDK_BUILDER_PATH)/build_flags.mak

# These flags are only needed within this repo
ifeq ($(SOC),am62a)
    BUILD_VIDEO_IO_KERNELS=yes
    BUILD_CAPTURE=yes
    BUILD_CSITX=no
    BUILD_DISPLAY=no
    BUILD_DISPLAY_M2M?=no
    BUILD_CT_TIOVX_VIDEO_IO=yes
    BUILD_CT_TIOVX_VIDEO_IO_CAPTURE_TESTS=yes
    BUILD_CT_TIOVX_VIDEO_IO_DISPLAY_TESTS=no
else ifeq ($(SOC),j722s)
    BUILD_VIDEO_IO_KERNELS?=yes
    BUILD_CAPTURE?=yes
    BUILD_CSITX?=yes
    BUILD_DISPLAY?=yes
    BUILD_DISPLAY_M2M?=no
    BUILD_CT_TIOVX_VIDEO_IO=yes
    BUILD_CT_TIOVX_VIDEO_IO_CAPTURE_TESTS=yes
    BUILD_CT_TIOVX_VIDEO_IO_DISPLAY_TESTS=yes
else ifeq ($(SOC),tda54)
    BUILD_VIDEO_IO_KERNELS?=yes
    BUILD_CAPTURE?=no
    BUILD_CSITX?=no
    BUILD_DISPLAY?=yes
    BUILD_DISPLAY_M2M?=yes
    BUILD_CT_TIOVX_VIDEO_IO=yes
    BUILD_CT_TIOVX_VIDEO_IO_CAPTURE_TESTS=no
    BUILD_CT_TIOVX_VIDEO_IO_DISPLAY_TESTS=yes
else
    BUILD_VIDEO_IO_KERNELS?=yes
    BUILD_CAPTURE?=yes
    BUILD_CSITX?=yes
    BUILD_DISPLAY?=yes
    BUILD_DISPLAY_M2M?=yes
    BUILD_CT_TIOVX_VIDEO_IO=yes
    BUILD_CT_TIOVX_VIDEO_IO_CAPTURE_TESTS=yes
    BUILD_CT_TIOVX_VIDEO_IO_DISPLAY_TESTS=yes
endif

