/********************************************************************
*
* DRU_R30_UTCL_32CH_WRAP1 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2025 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_DRU_R30_UTCL_32CH_WRAP1_INTERRUPT_MAP_H_
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: DRU_R30_UTCL_32CH_WRAP1
*/

#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_0           (0U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_1           (1U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_2           (2U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_3           (3U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_4           (4U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_5           (5U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_6           (6U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_7           (7U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_8           (8U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_9           (9U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_10          (10U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_11          (11U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_12          (12U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_13          (13U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_14          (14U)
#define CSLR_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_IN_EVENT_UTC_DMA_ROUTER_INTROUTER0_OUTP_15          (15U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_DRU_R30_UTCL_32CH_WRAP1_INTERRUPT_MAP_H_ */

