/********************************************************************
*
* UTC_DMA_ROUTER_INTROUTER0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2025 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_UTC_DMA_ROUTER_INTROUTER0_INTERRUPT_MAP_H_
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: UTC_DMA_ROUTER_INTROUTER0
*/

#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_0                   (0U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_1                   (1U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_2                   (2U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_3                   (3U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_4                   (4U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_5                   (5U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_6                   (6U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_7                   (7U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_8                   (8U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_9                   (9U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_10                  (10U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_11                  (11U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_12                  (12U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_13                  (13U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_14                  (14U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_15                  (15U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_16                  (16U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_17                  (17U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_18                  (18U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_19                  (19U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_20                  (20U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_21                  (21U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_22                  (22U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_23                  (23U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_24                  (24U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_25                  (25U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_26                  (26U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_27                  (27U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_28                  (28U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_29                  (29U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_30                  (30U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_COMPLETE_31                  (31U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_0                      (32U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_1                      (33U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_2                      (34U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_3                      (35U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_4                      (36U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_5                      (37U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_6                      (38U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_7                      (39U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_8                      (40U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_9                      (41U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_10                     (42U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_11                     (43U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_12                     (44U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_13                     (45U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_14                     (46U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_15                     (47U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_16                     (48U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_17                     (49U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_18                     (50U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_19                     (51U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_20                     (52U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_21                     (53U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_22                     (54U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_23                     (55U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_24                     (56U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_25                     (57U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_26                     (58U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_27                     (59U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_28                     (60U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_29                     (61U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_30                     (62U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_ERROR_31                     (63U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_0            (64U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_1            (65U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_2            (66U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_3            (67U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_4            (68U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_5            (69U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_6            (70U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_7            (71U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_8            (72U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_9            (73U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_10           (74U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_11           (75U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_12           (76U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_13           (77U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_14           (78U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_15           (79U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_16           (80U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_17           (81U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_18           (82U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_19           (83U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_20           (84U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_21           (85U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_22           (86U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_23           (87U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_24           (88U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_25           (89U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_26           (90U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_27           (91U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_28           (92U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_29           (93U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_30           (94U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_LOCAL_OUT_EVENT_31           (95U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DRU_R30_UTCL_32CH_WRAP1_DRU_PROT_ERR_0                   (96U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_0                   (97U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_1                   (98U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_2                   (99U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_3                   (100U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_4                   (101U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_5                   (102U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_6                   (103U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_7                   (104U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_0                   (105U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_1                   (106U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_2                   (107U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_3                   (108U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_4                   (109U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_5                   (110U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_6                   (111U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_7                   (112U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_0                             (113U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_1                             (114U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_2                             (115U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_3                             (116U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_4                             (117U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_5                             (118U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_6                             (119U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_7                             (120U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_0                        (121U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_1                        (122U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_2                        (123U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_3                        (124U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_4                        (125U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_5                        (126U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_6                        (127U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_7                        (128U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_CSI_RX_IF0_CSI_ERR_IRQ_0                                 (129U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_CSI_RX_IF0_CSI_IRQ_0                                     (130U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_CSI_RX_IF0_CSI_LEVEL_0                                   (131U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_CSI_TX_IF0_CSI_INTERRUPT_0                               (132U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_CSI_TX_IF0_CSI_LEVEL_0                                   (133U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_0                    (134U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_1                    (135U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_2                    (136U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_3                    (137U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_4                    (138U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_5                    (139U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_6                    (140U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_7                    (141U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_31                    (142U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_32                    (143U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_33                    (144U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_34                    (145U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_35                    (146U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_36                    (147U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_37                    (148U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_38                    (149U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_39                    (150U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_40                    (151U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_41                    (152U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_42                    (153U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_43                    (154U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_44                    (155U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_45                    (156U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_46                    (157U)
#define CSLR_UTC_DMA_ROUTER_INTROUTER0_IN_FSS_XSPI0_XSPI_SSI_TXAF_0                                (158U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_UTC_DMA_ROUTER_INTROUTER0_INTERRUPT_MAP_H_ */

