/********************************************************************
*
* R5FSS0_CORE1 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2025 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_R5FSS0_CORE1_INTERRUPT_MAP_H_
#define CSLR_R5FSS0_CORE1_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: R5FSS0_CORE1
*/

#define CSLR_R5FSS0_CORE1_INTR_CTRL_MMR0_IPC_SET17_IPC_SET_IPCFG_0                                 (0U)
#define CSLR_R5FSS0_CORE1_INTR_SMS0_AESEIP38T_0_AES_SINTREQUEST_P_0                                (1U)
#define CSLR_R5FSS0_CORE1_INTR_SMS0_AESEIP38T_0_AES_SINTREQUEST_S_0                                (2U)
#define CSLR_R5FSS0_CORE1_INTR_R5FSS0_CORE1_EXP_INTR_0                                             (4U)
#define CSLR_R5FSS0_CORE1_INTR_R5FSS0_COMMON0_COMMRX_LEVEL_1_0                                     (5U)
#define CSLR_R5FSS0_CORE1_INTR_R5FSS0_COMMON0_COMMTX_LEVEL_1_0                                     (6U)
#define CSLR_R5FSS0_CORE1_INTR_SA3_SS0_INTAGGR_0_INTAGGR_VINTR_7                                   (7U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_168                             (8U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_169                             (9U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_170                             (10U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_171                             (11U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_172                             (12U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_173                             (13U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_174                             (14U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_175                             (15U)
#define CSLR_R5FSS0_CORE1_INTR_SA3_SS0_SA_UL_0_SA_UL_PKA_0                                         (16U)
#define CSLR_R5FSS0_CORE1_INTR_SA3_SS0_SA_UL_0_SA_UL_TRNG_0                                        (17U)
#define CSLR_R5FSS0_CORE1_INTR_SMS0_TIFS_CBASS_0_FW_EXCEPTION_INTR_0                               (19U)
#define CSLR_R5FSS0_CORE1_INTR_SMS0_COMMON_0_COMBINED_SEC_IN_0                                     (20U)
#define CSLR_R5FSS0_CORE1_INTR_SMS0_HSM_CBASS_0_FW_EXCEPTION_INTR_0                                (21U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER6_INTR_PEND_0                                                  (22U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER7_INTR_PEND_0                                                  (23U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER0_INTR_PEND_0                                                  (24U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER1_INTR_PEND_0                                                  (25U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER2_INTR_PEND_0                                                  (26U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER3_INTR_PEND_0                                                  (27U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER4_INTR_PEND_0                                                  (28U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER5_INTR_PEND_0                                                  (29U)
#define CSLR_R5FSS0_CORE1_INTR_RTI1_INTR_WWD_0                                                     (30U)
#define CSLR_R5FSS0_CORE1_INTR_GLUELOGIC_MCU_CBASS_INTR_ERR_GLUE_OUT_0                             (31U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_16                                     (32U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_17                                     (33U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_18                                     (34U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_19                                     (35U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_20                                     (36U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_21                                     (37U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_22                                     (38U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_23                                     (39U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_24                                     (40U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_25                                     (41U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_26                                     (42U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_27                                     (43U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_28                                     (44U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_29                                     (45U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_30                                     (46U)
#define CSLR_R5FSS0_CORE1_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_31                                     (47U)
#define CSLR_R5FSS0_CORE1_INTR_CPSW0_CPTS_COMP_0                                                   (48U)
#define CSLR_R5FSS0_CORE1_INTR_RL2_OF_CBA4_1_ERR_LVL_0                                             (49U)
#define CSLR_R5FSS0_CORE1_INTR_I2C1_POINTRPEND_0                                                   (53U)
#define CSLR_R5FSS0_CORE1_INTR_UART3_USART_IRQ_0                                                   (54U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_152                             (64U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_153                             (65U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_154                             (66U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_155                             (67U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_156                             (68U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_157                             (69U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_158                             (70U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_159                             (71U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_160                             (72U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_161                             (73U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_162                             (74U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_163                             (75U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_164                             (76U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_165                             (77U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_166                             (78U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_167                             (79U)
#define CSLR_R5FSS0_CORE1_INTR_EPWM0_EPWM_TRIPZINT_0                                               (80U)
#define CSLR_R5FSS0_CORE1_INTR_EPWM1_EPWM_TRIPZINT_0                                               (81U)
#define CSLR_R5FSS0_CORE1_INTR_EPWM2_EPWM_TRIPZINT_0                                               (82U)
#define CSLR_R5FSS0_CORE1_INTR_ECAP0_ECAP_INT_0                                                    (83U)
#define CSLR_R5FSS0_CORE1_INTR_ECAP1_ECAP_INT_0                                                    (84U)
#define CSLR_R5FSS0_CORE1_INTR_ECAP2_ECAP_INT_0                                                    (85U)
#ifdef CSL_MODIFICATION
#define CSLR_R5FSS0_CORE1_INTR_RL2_OF_CBA4_0_ERR_LVL_0                                             (89U)
#define CSLR_R5FSS0_CORE1_INTR_RL2_OF_CBA4_1_ERR_LVL_0                                             (90U)
#define CSLR_R5FSS0_CORE1_INTR_RL2_OF_CBA4_2_ERR_LVL_0                                             (91U)
#define CSLR_R5FSS0_CORE1_INTR_RL2_OF_CBA4_3_ERR_LVL_0                                             (92U)
#endif
#define CSLR_R5FSS0_CORE1_INTR_R5FSS0_CORE1_PMU_0                                                  (93U)
#define CSLR_R5FSS0_CORE1_INTR_R5FSS0_CORE0_PMU_0                                                  (94U)
#define CSLR_R5FSS0_CORE1_INTR_R5FSS0_CORE1_VALFIQ_0                                               (95U)
#define CSLR_R5FSS0_CORE1_INTR_R5FSS0_CORE1_VALIRQ_0                                               (96U)
#define CSLR_R5FSS0_CORE1_INTR_WKUP_RTCSS0_RTC_EVENT_PEND_0                                        (97U)
#define CSLR_R5FSS0_CORE1_INTR_EFUSE0_EFC_ERROR_0                                                  (98U)
#define CSLR_R5FSS0_CORE1_INTR_MCU_DCC0_INTR_DONE_LEVEL_0                                          (108U)
#define CSLR_R5FSS0_CORE1_INTR_GLUELOGIC_MAIN_DCC_DONE_GLUE_DCC_DONE_0                             (109U)
#define CSLR_R5FSS0_CORE1_INTR_SMS0_RAT_1_EXP_INTR_0                                               (111U)
#define CSLR_R5FSS0_CORE1_INTR_SMS0_RAT_0_EXP_INTR_0                                               (112U)
#define CSLR_R5FSS0_CORE1_INTR_GLUELOGIC_MAIN_PBIST_CPU_GLUE_OUT_0                                 (113U)
#define CSLR_R5FSS0_CORE1_INTR_GLUELOGIC_WKUP_PBIST_CPUINTR_OUT_0                                  (114U)
#define CSLR_R5FSS0_CORE1_INTR_EPWM0_EPWM_ETINT_0                                                  (115U)
#define CSLR_R5FSS0_CORE1_INTR_EPWM1_EPWM_ETINT_0                                                  (116U)
#define CSLR_R5FSS0_CORE1_INTR_EPWM2_EPWM_ETINT_0                                                  (117U)
#define CSLR_R5FSS0_CORE1_INTR_MCRC_REV_POLY0_INT_MCRC_0                                           (119U)
#define CSLR_R5FSS0_CORE1_INTR_GLUELOGIC_SOC_ACCESS_ERR_INTR_GLUE_OUT_0                            (128U)
#define CSLR_R5FSS0_CORE1_INTR_CPSW0_EVNT_PEND_0                                                   (134U)
#define CSLR_R5FSS0_CORE1_INTR_CPSW0_MDIO_PEND_0                                                   (135U)
#define CSLR_R5FSS0_CORE1_INTR_CPSW0_STAT_PEND_0                                                   (136U)
#define CSLR_R5FSS0_CORE1_INTR_MCU_DCC1_INTR_DONE_LEVEL_0                                          (137U)
#define CSLR_R5FSS0_CORE1_INTR_WKUP_PSC0_PSC_ALLINT_0                                              (145U)
#define CSLR_R5FSS0_CORE1_INTR_PSCSS0_PSC_ALLINT_0                                                 (146U)
#define CSLR_R5FSS0_CORE1_INTR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_CBASS_AGG_ERR_INTR_0         (147U)
#define CSLR_R5FSS0_CORE1_INTR_ADC0_GEN_LEVEL_0                                                    (151U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_176                             (153U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_177                             (154U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_178                             (155U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_179                             (156U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_180                             (157U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_181                             (158U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_182                             (159U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_183                             (160U)
#define CSLR_R5FSS0_CORE1_INTR_CSI_RX_IF0_CSI_ERR_IRQ_0                                            (161U)
#define CSLR_R5FSS0_CORE1_INTR_CSI_RX_IF0_CSI_IRQ_0                                                (162U)
#define CSLR_R5FSS0_CORE1_INTR_CSI_RX_IF0_CSI_LEVEL_0                                              (163U)
#define CSLR_R5FSS0_CORE1_INTR_CSI_TX_IF0_CSI_INTERRUPT_0                                          (164U)
#define CSLR_R5FSS0_CORE1_INTR_CSI_TX_IF0_CSI_LEVEL_0                                              (165U)
#define CSLR_R5FSS0_CORE1_INTR_ESM0_ESM_INT_CFG_LVL_0                                              (167U)
#define CSLR_R5FSS0_CORE1_INTR_ESM0_ESM_INT_HI_LVL_0                                               (168U)
#define CSLR_R5FSS0_CORE1_INTR_ESM0_ESM_INT_LOW_LVL_0                                              (169U)
#define CSLR_R5FSS0_CORE1_INTR_FSS0_FSAS_FOTA_STAT_INTR_PEND_0                                     (172U)
#define CSLR_R5FSS0_CORE1_INTR_FSS0_FSAS_FOTA_STAT_ERR_PEND_0                                      (173U)
#define CSLR_R5FSS0_CORE1_INTR_FSS0_FSAS_ECC_INTR_ERR_PEND_0                                       (174U)
#define CSLR_R5FSS0_CORE1_INTR_R5FSS0_CORE0_CTI_0                                                  (175U)
#define CSLR_R5FSS0_CORE1_INTR_R5FSS0_CORE1_CTI_0                                                  (176U)
#define CSLR_R5FSS0_CORE1_INTR_DDPA0_DDPA_INTR_0                                                   (177U)
#define CSLR_R5FSS0_CORE1_INTR_FSS0_OSPI0_LVL_INTR_0                                               (178U)
#define CSLR_R5FSS0_CORE1_INTR_FSS0_OTFA_INTR_ERR_PEND_0                                           (179U)
#define CSLR_R5FSS0_CORE1_INTR_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                                   (183U)
#define CSLR_R5FSS0_CORE1_INTR_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                                   (184U)
#define CSLR_R5FSS0_CORE1_INTR_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                                   (185U)
#define CSLR_R5FSS0_CORE1_INTR_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (186U)
#define CSLR_R5FSS0_CORE1_INTR_WKUP_I2C0_POINTRPEND_0                                              (190U)
#define CSLR_R5FSS0_CORE1_INTR_I2C0_POINTRPEND_0                                                   (193U)
#define CSLR_R5FSS0_CORE1_INTR_DEBUGSS0_AQCMPINTR_LEVEL_0                                          (201U)
#define CSLR_R5FSS0_CORE1_INTR_DEBUGSS0_CTM_LEVEL_0                                                (202U)
#define CSLR_R5FSS0_CORE1_INTR_GLUELOGIC_EXT_INTN_GLUE_OUT_0                                       (203U)
#define CSLR_R5FSS0_CORE1_INTR_MCSPI0_INTR_SPI_0                                                   (204U)
#define CSLR_R5FSS0_CORE1_INTR_MCSPI1_INTR_SPI_0                                                   (205U)
#define CSLR_R5FSS0_CORE1_INTR_MCSPI2_INTR_SPI_0                                                   (206U)
#define CSLR_R5FSS0_CORE1_INTR_UART0_USART_IRQ_0                                                   (210U)
#define CSLR_R5FSS0_CORE1_INTR_UART1_USART_IRQ_0                                                   (211U)
#define CSLR_R5FSS0_CORE1_INTR_UART2_USART_IRQ_0                                                   (212U)
#define CSLR_R5FSS0_CORE1_INTR_WKUP_UART0_USART_IRQ_0                                              (219U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_0                                        (220U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_1                                        (221U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_2                                        (222U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_3                                        (223U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_4                                        (224U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_5                                        (225U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_6                                        (226U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_7                                        (227U)
#define CSLR_R5FSS0_CORE1_INTR_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (229U)
#define CSLR_R5FSS0_CORE1_INTR_MCAN0_MCANSS_MCAN_LVL_INT_0                                         (230U)
#define CSLR_R5FSS0_CORE1_INTR_MCAN0_MCANSS_MCAN_LVL_INT_1                                         (231U)
#define CSLR_R5FSS0_CORE1_INTR_MCAN1_MCANSS_MCAN_LVL_INT_0                                         (232U)
#define CSLR_R5FSS0_CORE1_INTR_MCAN1_MCANSS_MCAN_LVL_INT_1                                         (233U)
#define CSLR_R5FSS0_CORE1_INTR_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER_PEND_1                   (240U)
#define CSLR_R5FSS0_CORE1_INTR_MAILBOX0_MAILBOX_CLUSTER_2_MAILBOX_CLUSTER_PEND_0                   (241U)
#define CSLR_R5FSS0_CORE1_INTR_MAILBOX0_MAILBOX_CLUSTER_3_MAILBOX_CLUSTER_PEND_1                   (242U)
#define CSLR_R5FSS0_CORE1_INTR_MAILBOX0_MAILBOX_CLUSTER_6_MAILBOX_CLUSTER_PEND_1                   (243U)
#define CSLR_R5FSS0_CORE1_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_0                                (248U)
#define CSLR_R5FSS0_CORE1_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_1                                (249U)
#define CSLR_R5FSS0_CORE1_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_2                                (250U)
#define CSLR_R5FSS0_CORE1_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_3                                (251U)
#define CSLR_R5FSS0_CORE1_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_4                                (252U)
#define CSLR_R5FSS0_CORE1_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_5                                (253U)
#define CSLR_R5FSS0_CORE1_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_6                                (254U)
#define CSLR_R5FSS0_CORE1_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_7                                (255U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_0                               (256U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_1                               (257U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_2                               (258U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_3                               (259U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_4                               (260U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_5                               (261U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_6                               (262U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_7                               (263U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER8_INTR_PEND_0                                                  (264U)
#define CSLR_R5FSS0_CORE1_INTR_TIMER9_INTR_PEND_0                                                  (265U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_8                               (280U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_9                               (281U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_10                              (282U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_11                              (283U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_12                              (284U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_13                              (285U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_14                              (286U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_15                              (287U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_0                                   (288U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_1                                   (289U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_2                                   (290U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_3                                   (291U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_4                                   (292U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_5                                   (293U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_6                                   (294U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA_INTR_O_FSM2_7                                   (295U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_0                              (296U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_1                              (297U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_2                              (298U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_3                              (299U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_4                              (300U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_5                              (301U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_6                              (302U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_7                              (303U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_8                              (304U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_9                              (305U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_10                             (306U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_11                             (307U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_12                             (308U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_13                             (309U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_14                             (310U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_15                             (311U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_16                             (312U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_17                             (313U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_18                             (314U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_19                             (315U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_20                             (316U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_21                             (317U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_22                             (318U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_23                             (319U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_24                             (320U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_25                             (321U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_26                             (322U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_27                             (323U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_28                             (324U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_29                             (325U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_30                             (326U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM1_31                             (327U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_0                              (328U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_1                              (329U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_2                              (330U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_3                              (331U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_4                              (332U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_5                              (333U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_6                              (334U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_7                              (335U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_8                              (336U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_9                              (337U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_10                             (338U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_11                             (339U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_12                             (340U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_13                             (341U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_14                             (342U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_15                             (343U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_16                             (344U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_17                             (345U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_18                             (346U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_19                             (347U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_20                             (348U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_21                             (349U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_22                             (350U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_23                             (351U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_24                             (352U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_25                             (353U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_26                             (354U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_27                             (355U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_28                             (356U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_29                             (357U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_30                             (358U)
#define CSLR_R5FSS0_CORE1_INTR_RADAR_HWA0_RPAC_HWA2DMA_TRIGGER_FSM2_31                             (359U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_INTG_PO_0                                              (400U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_INT_PO_0                                               (401U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_INT_PO_1                                               (402U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_INT_PO_2                                               (403U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_INT_PO_3                                               (404U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_INT_PO_4                                               (405U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_INT_PO_5                                               (406U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_INT_PO_6                                               (407U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_INT_PO_7                                               (408U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPTC_A0_INT_PO_0                                              (409U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPTC_A1_INT_PO_0                                              (410U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_16                              (411U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_17                              (412U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_18                              (413U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_19                              (414U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_20                              (415U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_21                              (416U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_22                              (417U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_23                              (418U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_24                              (419U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_25                              (420U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_26                              (421U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_27                              (422U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_28                              (423U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_29                              (424U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_30                              (425U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_31                              (426U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_32                              (427U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_33                              (428U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_34                              (429U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_35                              (430U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_36                              (431U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_ERRINT_PO_0                                            (432U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_PARITY_ERR_0                                           (433U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_READ_ERR_0                                             (434U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_WRITE_ERR_0                                            (435U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPTC_A0_ERINT_PO_0                                            (436U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPTC_A0_READ_ERR_0                                            (437U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPTC_A0_WRITE_ERR_0                                           (438U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPTC_A1_ERINT_PO_0                                            (439U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPTC_A1_READ_ERR_0                                            (440U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPTC_A1_WRITE_ERR_0                                           (441U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_37                              (442U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_38                              (443U)
#define CSLR_R5FSS0_CORE1_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_39                              (444U)
#define CSLR_R5FSS0_CORE1_INTR_EDMA1_TPCC_A_MPINT_PO_0                                             (496U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_R5FSS0_CORE1_INTERRUPT_MAP_H_ */

