/********************************************************************
*
* C7X256V0_CLEC INTERRUPT MAP. header file
*
* Copyright (C) 2015-2025 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_C7X256V0_CLEC_INTERRUPT_MAP_H_
#define CSLR_C7X256V0_CLEC_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: C7X256V0_CLEC
*/

#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_RTI4_INTR_WWD_0                                           (4U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_CTRL_MMR0_IPC_SET0_IPC_SET_IPCFG_0                        (5U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_MAILBOX0_MAILBOX_CLUSTER_1_MAILBOX_CLUSTER_PEND_2         (6U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_MAILBOX0_MAILBOX_CLUSTER_2_MAILBOX_CLUSTER_PEND_2         (7U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_MAILBOX0_MAILBOX_CLUSTER_3_MAILBOX_CLUSTER_PEND_2         (8U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_MAILBOX0_MAILBOX_CLUSTER_4_MAILBOX_CLUSTER_PEND_2         (9U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_MAILBOX0_MAILBOX_CLUSTER_7_MAILBOX_CLUSTER_PEND_1         (10U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_84                    (16U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_85                    (17U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_86                    (18U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_87                    (19U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_88                    (20U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_89                    (21U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_90                    (22U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_91                    (23U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_92                    (24U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_93                    (25U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_94                    (26U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_95                    (27U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_96                    (28U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_97                    (29U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_98                    (30U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_99                    (31U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_0                                  (32U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_1                                  (33U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_2                                  (34U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_3                                  (35U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_4                                  (36U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_5                                  (37U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_6                                  (38U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_7                                  (39U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_8                                  (40U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_9                                  (41U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_10                                 (42U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_11                                 (43U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_12                                 (44U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_13                                 (45U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_14                                 (46U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_15                                 (47U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CPSW0_CPTS_COMP_0                                               (48U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_ERRINT_PO_0                                        (49U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_INT_PO_0                                           (50U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_INT_PO_1                                           (51U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_INT_PO_2                                           (52U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_INT_PO_3                                           (53U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_INT_PO_4                                           (54U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_INT_PO_5                                           (55U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_INT_PO_6                                           (56U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_INT_PO_7                                           (57U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_INTG_PO_0                                          (58U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_MPINT_PO_0                                         (59U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_PARITY_ERR_0                                       (60U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_READ_ERR_0                                         (61U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPCC_A_WRITE_ERR_0                                        (62U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPTC_A0_ERINT_PO_0                                        (63U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER8_INTR_PEND_0                                              (64U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER9_INTR_PEND_0                                              (65U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPTC_A0_INT_PO_0                                          (66U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPTC_A0_READ_ERR_0                                        (67U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPTC_A0_WRITE_ERR_0                                       (68U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPTC_A1_ERINT_PO_0                                        (69U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPTC_A1_INT_PO_0                                          (70U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPTC_A1_READ_ERR_0                                        (71U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EDMA1_TPTC_A1_WRITE_ERR_0                                       (72U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CSI_RX_IF0_CSI_ERR_IRQ_0                                        (73U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CSI_RX_IF0_CSI_IRQ_0                                            (74U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CSI_RX_IF0_CSI_LEVEL_0                                          (75U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CSI_TX_IF0_CSI_INTERRUPT_0                                      (76U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CSI_TX_IF0_CSI_LEVEL_0                                          (77U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_0                           (78U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_1                           (79U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_I2C1_POINTRPEND_0                                               (83U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART3_USART_IRQ_0                                               (84U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_0                                        (85U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_1                                        (86U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_2                                        (87U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_3                                        (88U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_4                                        (89U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_5                                        (90U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_6                                        (91U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_7                                        (92U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_8                                        (93U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_9                                        (94U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_10                                       (95U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_32                          (96U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_33                          (97U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_34                          (98U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_35                          (99U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_36                          (100U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_37                          (101U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_38                          (102U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_39                          (103U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_11                                       (104U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_12                                       (105U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_13                                       (106U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_14                                       (107U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_15                                       (108U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_16                                       (109U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_17                                       (110U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_18                                       (111U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SA3_SS0_INTAGGR_0_INTAGGR_VINTR_4                               (112U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SA3_SS0_INTAGGR_0_INTAGGR_VINTR_5                               (113U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_19                                       (114U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_20                                       (115U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_21                                       (116U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_22                                       (117U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_23                                       (118U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_24                                       (119U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_25                                       (120U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_26                                       (121U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_27                                       (122U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_28                                       (123U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_29                                       (124U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_30                                       (125U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_C7XV_0_INTROUTER1_OUTP_31                                       (126U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_2                           (127U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_MAIN_DCC_DONE_GLUE_DCC_DONE_0                         (128U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_SOC_ACCESS_ERR_INTR_GLUE_OUT_0                        (129U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_3                           (130U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EFUSE0_EFC_ERROR_0                                              (131U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_RTCSS0_RTC_EVENT_PEND_0                                    (132U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_CBASS_AGG_ERR_INTR_0     (133U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CPSW0_EVNT_PEND_0                                               (134U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CPSW0_MDIO_PEND_0                                               (135U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CPSW0_STAT_PEND_0                                               (136U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_4                           (137U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_5                           (138U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_6                           (139U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_7                           (140U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_8                           (141U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_9                           (142U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SMS0_TIFS_CBASS_0_FW_EXCEPTION_INTR_0                           (143U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SMS0_COMMON_0_COMBINED_SEC_IN_0                                 (144U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ECAP0_ECAP_INT_0                                                (145U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ECAP1_ECAP_INT_0                                                (146U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ECAP2_ECAP_INT_0                                                (147U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_10                          (148U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_11                          (149U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_12                          (150U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ADC0_GEN_LEVEL_0                                                (151U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER0_INTR_PEND_0                                              (152U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER1_INTR_PEND_0                                              (153U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER2_INTR_PEND_0                                              (154U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER3_INTR_PEND_0                                              (155U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER4_INTR_PEND_0                                              (156U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER5_INTR_PEND_0                                              (157U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER6_INTR_PEND_0                                              (158U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER7_INTR_PEND_0                                              (159U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SA3_SS0_SA_UL_0_SA_UL_PKA_0                                     (160U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SA3_SS0_SA_UL_0_SA_UL_TRNG_0                                    (161U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_13                          (162U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_14                          (163U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_15                          (164U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_16                          (165U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCRC_REV_POLY0_INT_MCRC_0                                       (166U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_17                          (167U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_18                          (168U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_19                          (169U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_FSS0_FSAS_ECC_INTR_ERR_PEND_0                                   (170U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_20                          (171U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_FSS0_FSAS_FOTA_STAT_INTR_PEND_0                                 (172U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_FSS0_FSAS_FOTA_STAT_ERR_PEND_0                                  (173U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_21                          (174U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_22                          (175U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SMS0_AESEIP38T_0_AES_SINTREQUEST_P_0                            (176U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DDPA0_DDPA_INTR_0                                               (177U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_23                          (178U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_24                          (179U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ESM0_ESM_INT_CFG_LVL_0                                          (180U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ESM0_ESM_INT_HI_LVL_0                                           (181U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ESM0_ESM_INT_LOW_LVL_0                                          (182U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                               (183U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                               (184U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                               (185U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (186U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCAN0_MCANSS_MCAN_LVL_INT_0                                     (187U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCAN0_MCANSS_MCAN_LVL_INT_1                                     (188U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_25                          (189U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_26                          (190U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_27                          (191U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_28                          (192U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_I2C0_POINTRPEND_0                                               (193U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_29                          (194U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_30                          (195U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_31                          (196U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_I2C0_POINTRPEND_0                                          (197U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SMS0_AESEIP38T_0_AES_SINTREQUEST_S_0                            (198U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (199U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_32                          (200U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DEBUGSS0_AQCMPINTR_LEVEL_0                                      (201U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DEBUGSS0_CTM_LEVEL_0                                            (202U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_PSCSS0_PSC_ALLINT_0                                             (203U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCSPI0_INTR_SPI_0                                               (204U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCSPI1_INTR_SPI_0                                               (205U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCSPI2_INTR_SPI_0                                               (206U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_33                          (207U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_34                          (208U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_35                          (209U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART0_USART_IRQ_0                                               (210U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART1_USART_IRQ_0                                               (211U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART2_USART_IRQ_0                                               (212U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_36                          (213U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_37                          (214U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_38                          (215U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_39                          (216U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_FSS0_OSPI0_LVL_INTR_0                                           (217U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_UART0_USART_IRQ_0                                          (218U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_FSS0_OTFA_INTR_ERR_PEND_0                                       (219U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM0_EPWM_ETINT_0                                              (229U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM0_EPWM_TRIPZINT_0                                           (230U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM1_EPWM_ETINT_0                                              (231U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM1_EPWM_TRIPZINT_0                                           (233U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM2_EPWM_ETINT_0                                              (234U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM2_EPWM_TRIPZINT_0                                           (235U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCAN1_MCANSS_MCAN_LVL_INT_0                                     (245U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCAN1_MCANSS_MCAN_LVL_INT_1                                     (246U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_EXT_INTN_GLUE_OUT_0                                   (256U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_RL2_OF_CBA4_0_ERR_LVL_0                                         (260U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_RL2_OF_CBA4_1_ERR_LVL_0                                         (261U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_RL2_OF_CBA4_2_ERR_LVL_0                                         (262U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_RL2_OF_CBA4_3_ERR_LVL_0                                         (263U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_C7X256V0_CLEC_INTERRUPT_MAP_H_ */

