/********************************************************************
*
* WKUP_R5FSS0_CORE0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2025 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_WKUP_R5FSS0_CORE0_INTERRUPT_MAP_H_
#define CSLR_WKUP_R5FSS0_CORE0_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: WKUP_R5FSS0_CORE0
*/

#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCU_CTRL_MMR0_IPC_SET0_IPC_SET_IPCFG_0                         (0U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SMS0_AESEIP38T_0_AES_SINTREQUEST_P_0                           (1U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SMS0_AESEIP38T_0_AES_SINTREQUEST_S_0                           (2U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GLUELOGIC_LBIST_DONE_GLUE_OUT_0                                (3U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_R5FSS0_CORE0_EXP_INTR_0                                   (4U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_R5FSS0_COMMON0_COMMRX_LEVEL_0_0                           (5U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_R5FSS0_COMMON0_COMMTX_LEVEL_0_0                           (6U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SA3_SS0_INTAGGR_0_INTAGGR_VINTR_6                              (7U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_72                         (8U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_73                         (9U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_74                         (10U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_75                         (11U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_76                         (12U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_77                         (13U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_78                         (14U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_79                         (15U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SA3_SS0_SA_UL_0_SA_UL_PKA_0                                    (16U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SA3_SS0_SA_UL_0_SA_UL_TRNG_0                                   (17U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_ERRINT_PO_0                                       (18U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SMS0_TIFS_CBASS_0_FW_EXCEPTION_INTR_0                          (19U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SMS0_COMMON_0_COMBINED_SEC_IN_0                                (20U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SMS0_HSM_CBASS_0_FW_EXCEPTION_INTR_0                           (21U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GLUELOGIC_DEBUG_FORCE_DEACTIVE_OUT_0                           (22U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_ICEMELTER0_PSC_FORCE_POWER_ON_0                           (23U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_INT_PO_0                                          (24U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_INT_PO_1                                          (25U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_INT_PO_2                                          (26U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DEEPSLEEP_SOURCES0_WAKEUP_EVENT_0                         (27U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_TIMER0_TIMER_CLKSTOP_WAKEUP_0                             (28U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_TIMER1_TIMER_CLKSTOP_WAKEUP_0                             (29U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_RTI0_INTR_WWD_0                                           (30U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_INT_PO_3                                          (31U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_0                                 (32U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_1                                 (33U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_2                                 (34U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_3                                 (35U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_4                                 (36U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_5                                 (37U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_6                                 (38U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_7                                 (39U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_8                                 (40U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_9                                 (41U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_10                                (42U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_11                                (43U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_12                                (44U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_13                                (45U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_14                                (46U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_15                                (47U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_CPSW0_CPTS_COMP_0                                              (48U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_INT_PO_4                                          (49U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_FSS0_FSAS_ECC_INTR_ERR_PEND_0                                  (51U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_FSS0_OSPI0_LVL_INTR_0                                          (52U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_I2C1_POINTRPEND_0                                              (53U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_UART3_USART_IRQ_0                                              (54U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_INT_PO_5                                          (55U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GPIO0_GPIO_BANK_0                                              (56U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GPIO0_GPIO_BANK_1                                              (57U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_R5FSS0_CORE0_PMU_0                                        (58U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_R5FSS0_CORE0_VALFIQ_0                                     (59U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_R5FSS0_CORE0_VALIRQ_0                                     (60U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_INT_PO_6                                          (61U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_INT_PO_7                                          (62U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_INTG_PO_0                                         (63U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_40                         (64U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_41                         (65U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_42                         (66U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_43                         (67U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_44                         (68U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_45                         (69U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_46                         (70U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_47                         (71U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_48                         (72U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_49                         (73U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_50                         (74U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_51                         (75U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_52                         (76U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_53                         (77U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_54                         (78U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_55                         (79U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_56                         (80U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_57                         (81U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_58                         (82U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_59                         (83U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_60                         (84U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_61                         (85U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_62                         (86U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_63                         (87U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_64                         (88U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_65                         (89U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_66                         (90U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_67                         (91U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_68                         (92U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_69                         (93U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_70                         (94U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_71                         (95U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_MPINT_PO_0                                        (96U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_RTCSS0_RTC_EVENT_PEND_0                                   (97U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EFUSE0_EFC_ERROR_0                                             (98U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_PARITY_ERR_0                                      (99U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_READ_ERR_0                                        (100U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPCC_A_WRITE_ERR_0                                       (101U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPTC_A0_ERINT_PO_0                                       (102U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPTC_A0_INT_PO_0                                         (103U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPTC_A0_READ_ERR_0                                       (104U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPTC_A0_WRITE_ERR_0                                      (105U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPTC_A1_ERINT_PO_0                                       (106U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPTC_A1_INT_PO_0                                         (107U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCU_DCC0_INTR_DONE_LEVEL_0                                     (108U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GLUELOGIC_MAIN_DCC_DONE_GLUE_DCC_DONE_0                        (109U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPTC_A1_READ_ERR_0                                       (110U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SMS0_RAT_1_EXP_INTR_0                                          (111U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_SMS0_RAT_0_EXP_INTR_0                                          (112U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GLUELOGIC_MAIN_PBIST_CPU_GLUE_OUT_0                            (113U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GLUELOGIC_WKUP_PBIST_CPUINTR_OUT_0                             (114U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EDMA1_TPTC_A1_WRITE_ERR_0                                      (115U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_CSI_RX_IF0_CSI_ERR_IRQ_0                                       (116U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_CSI_RX_IF0_CSI_IRQ_0                                           (117U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_CSI_RX_IF0_CSI_LEVEL_0                                         (118U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCRC_REV_POLY0_INT_MCRC_0                                      (119U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_CSI_TX_IF0_CSI_INTERRUPT_0                                     (120U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_CSI_TX_IF0_CSI_LEVEL_0                                         (121U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_0                          (122U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EPWM0_EPWM_ETINT_0                                             (123U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EPWM0_EPWM_TRIPZINT_0                                          (124U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EPWM1_EPWM_ETINT_0                                             (125U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EPWM1_EPWM_TRIPZINT_0                                          (126U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EPWM2_EPWM_ETINT_0                                             (127U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GLUELOGIC_SOC_ACCESS_ERR_INTR_GLUE_OUT_0                       (128U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_1                          (129U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_2                          (130U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_3                          (131U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_4                          (132U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_5                          (133U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_CPSW0_EVNT_PEND_0                                              (134U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_CPSW0_MDIO_PEND_0                                              (135U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_CPSW0_STAT_PEND_0                                              (136U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCU_DCC1_INTR_DONE_LEVEL_0                                     (137U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_TIMER0_INTR_PEND_0                                        (138U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_TIMER1_INTR_PEND_0                                        (139U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_6                          (140U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_7                          (141U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_8                          (142U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_I2C0_CLKSTOP_WAKEUP_0                                     (143U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_UART0_CLKSTOP_WAKEUP_0                                    (144U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_PSC0_PSC_ALLINT_0                                         (145U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_PSCSS0_PSC_ALLINT_0                                            (146U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_CBASS_AGG_ERR_INTR_0    (147U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_EPWM2_EPWM_TRIPZINT_0                                          (148U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_9                          (149U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_10                         (150U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_ADC0_GEN_LEVEL_0                                               (151U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_0                                   (152U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_1                                   (153U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_2                                   (154U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_3                                   (155U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_4                                   (156U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_5                                   (157U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_6                                   (158U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_7                                   (159U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_8                                   (160U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_9                                   (161U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_10                                  (162U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_11                                  (163U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_12                                  (164U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_13                                  (165U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_14                                  (166U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_ESM0_ESM_INT_CFG_LVL_0                                         (167U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_ESM0_ESM_INT_HI_LVL_0                                          (168U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_ESM0_ESM_INT_LOW_LVL_0                                         (169U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_15                                  (170U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_16                                  (171U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_FSS0_FSAS_FOTA_STAT_INTR_PEND_0                                (172U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_FSS0_FSAS_FOTA_STAT_ERR_PEND_0                                 (173U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_17                                  (174U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_R5FSS0_CORE0_CTI_0                                        (175U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_18                                  (176U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DDPA0_DDPA_INTR_0                                              (177U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_19                                  (178U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_20                                  (179U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_21                                  (180U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_22                                  (181U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_11                         (182U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                              (183U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                              (184U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                              (185U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                         (186U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_23                                  (187U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_24                                  (188U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_25                                  (189U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_I2C0_POINTRPEND_0                                         (190U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_26                                  (191U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_27                                  (192U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_I2C0_POINTRPEND_0                                              (193U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_28                                  (194U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_29                                  (195U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_30                                  (196U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_DM_R5_INTROUTER0_OUTP_31                                  (197U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_12                         (198U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_13                         (199U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_14                         (200U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DEBUGSS0_AQCMPINTR_LEVEL_0                                     (201U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DEBUGSS0_CTM_LEVEL_0                                           (202U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GLUELOGIC_EXT_INTN_GLUE_OUT_0                                  (203U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCSPI0_INTR_SPI_0                                              (204U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCSPI1_INTR_SPI_0                                              (205U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCSPI2_INTR_SPI_0                                              (206U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_15                         (207U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_16                         (208U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_17                         (209U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_UART0_USART_IRQ_0                                              (210U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_UART1_USART_IRQ_0                                              (211U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_UART2_USART_IRQ_0                                              (212U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_18                         (213U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_19                         (214U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_20                         (215U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_21                         (216U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_22                         (217U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_23                         (218U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_WKUP_UART0_USART_IRQ_0                                         (219U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_24                         (220U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_25                         (221U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_26                         (222U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_27                         (223U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_28                         (224U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_29                         (225U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_30                         (226U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_31                         (227U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_32                         (228U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                         (229U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCAN0_MCANSS_MCAN_LVL_INT_0                                    (230U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCAN0_MCANSS_MCAN_LVL_INT_1                                    (231U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCAN1_MCANSS_MCAN_LVL_INT_0                                    (232U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MCAN1_MCANSS_MCAN_LVL_INT_1                                    (233U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_34                         (234U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_33                         (235U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_35                         (236U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_36                         (237U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_37                         (238U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_38                         (239U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAILBOX0_MAILBOX_CLUSTER_5_MAILBOX_CLUSTER_PEND_0              (240U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAILBOX0_MAILBOX_CLUSTER_6_MAILBOX_CLUSTER_PEND_0              (241U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_MAILBOX0_MAILBOX_CLUSTER_7_MAILBOX_CLUSTER_PEND_0              (242U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_39                         (243U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_FSS0_OTFA_INTR_ERR_PEND_0                                      (244U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_24                          (249U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_25                          (250U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_GLUELOGIC_IO_SWAKEUP_CAN_USART_IO_0                            (251U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_26                          (254U)
#define CSLR_WKUP_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_27                          (255U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_WKUP_R5FSS0_CORE0_INTERRUPT_MAP_H_ */

